#!zsh

# Login shell setup.
typeset -U path

path=(
  "$HOME/.local/bin"
  "/opt/homebrew/bin"
  "/usr/local/bin"
  "/usr/bin"
  "/bin"
  "/usr/local/sbin"
  "/usr/sbin"
  "/sbin"
)

export PATH="${(j.:.)path}"

export EDITOR="nvim"
export VISUAL="nvim"
export PAGER="less -R"

export ZSH_CACHE_DIR="${XDG_CACHE_HOME}/zsh"
export ZSH_SESSION_FILE="${XDG_STATE_HOME}/zsh/session"
mkdir -p "$ZSH_CACHE_DIR/zsh" "$XDG_STATE_HOME/zsh"
export ZIM_CONFIG_FILE="$ZDOTDIR/.zimrc"
export ZIM_HOME="$XDG_DATA_HOME/zim"

export HOMEBREW_PREFIX="${HOMEBREW_PREFIX:-/opt/homebrew}"
export HOMEBREW_BUNDLE_FILE="$XDG_CONFIG_HOME/Brewfile"
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_ENV_HINTS=1
export HOMEBREW_NO_INSTALL_FROM_API=1

export MISE_SHIMS_DIR="$XDG_DATA_HOME/mise/shims"
# export MISE_ENV_FILE=.env

export LESS="-g -i -w -M -R -F -X"
export LESSHISTFILE="$XDG_STATE_HOME/lesshst"

export MANPAGER="col -bx | bat -p -l man"

export TMUX_PLUGIN_MANAGER_PATH="$XDG_DATA_HOME/tmux/plugins"

export FZF_CTRL_R_OPTS="--reverse"

export GOPATH="$XDG_DATA_HOME/go"

export CODEX_HOME="$XDG_CONFIG_HOME/codex"

# Homebrew shellenv is expensive; avoid unless you really need it.
# If you must, do it here (login only), and only if brew exists.
# if command -v brew >/dev/null 2>&1; then
#   eval "$(brew shellenv)"
# fi

# vim: set ft=zsh
