#!zsh

# Interactive shell configuration.
setopt PROMPT_SUBST
setopt INTERACTIVE_COMMENTS
setopt AUTO_CD
setopt NO_BEEP

# History behavior
setopt APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY

HISTSIZE=200000
SAVEHIST=200000

# Load zimfw (generated init.zsh)
if [[ -r "$HOMEBREW_PREFIX/opt/zimfw/share/zimfw.zsh" ]] ; then
	source "$HOMEBREW_PREFIX/opt/zimfw/share/zimfw.zsh" init -q
fi
if [[ -s "$ZIM_HOME/init.zsh" ]]; then
	 source "$ZIM_HOME/init.zsh"
fi

# # Mise activation: do it for interactive shells
# if command -v mise >/dev/null 2>&1; then
#   # Prefer ONE method only: either shims on PATH or activate.
#   # Here we assume you use activation (recommended).
#   eval "$(mise activate zsh)"
# fi
#
# # Starship (if you use it)
# if command -v starship >/dev/null 2>&1; then
#   eval "$(starship init zsh)"
# fi

# Completion
# autoload -Uz compinit
# local compDump="${ZSH_CACHE_DIR}/zcompdump-${ZSH_VERSION}"
# # Rebuild if dump is missing or older than 1 day
# if [[ ! -f "$compDump" || "$compDump" -ot "${ZDOTDIR}/zshrc" ]]; then
#   compinit -d "$compDump"
# else
#   compinit -C -d "$compDump"
# fi
# zstyle ':completion:*' use-cache on
# zstyle ':completion:*' cache-path "${ZSH_CACHE_DIR}/zcompcache"
# zstyle ':completion:*' menu select
# zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
# zstyle ':completion:*' squeeze-slashes true
# zstyle ':completion:*' verbose false

if [[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/bindings.zsh" ]]; then
	source "$XDG_CONFIG_HOME/zsh/bindings.zsh"
fi
if [[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/zsh/aliases.zsh" ]]; then
	source "$XDG_CONFIG_HOME/zsh/aliases.zsh"
fi

if command -v zellij >/dev/null 2>&1; then
	export ZELLIJ_AUTO_ATTACH=true
	export ZELLIJ_AUTO_EXIT=false
	eval "$(zellij setup --generate-auto-start zsh)"
fi

# vim: set ft=zsh

