verbose = true

[git]
autoAdd = true
autoCommit = true
autoPush = false

[update]
apply = false

[diff]
command = "difft"
args = [
  "--skip-unchanged",
  "--sort-paths",
  "--color=always",
  "--syntax-highlight=on",
  "--display=side-by-side",
]

[merge]
command = "nvim"
args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]

[hooks.re-add.pre]
command = "chezmoi-commit"
args = ["hooks.re-add.pre"]

[hooks.apply.post]
command = "chezmoi-rebase"
args = ["hooks.apply.post"]

# vim: ft=toml
