verbose = true

[git]
autoAdd = true
autoCommit = true
autoPush = false

[update]
apply = false

[diff]
command = "difft"
args = [
  "--skip-unchanged",
  "--sort-paths",
  "--color=always",
  "--syntax-highlight=on",
  "--display=side-by-side",
]

[merge]
command = "nvim"
args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]

# [hooks.re-add]
# command = "chezmoi-packages"
# args = ["re-add"]

# [hooks.apply]
# command = "chezmoi-packages"
# args = ["apply"]

# vim: ft=toml
