verbose = true

[git]
autoAdd = true
autoCommit = true
autoPush = false

[update]
apply = false

[diff]
command = "difft"
args = [
  "--skip-unchanged",
  "--sort-paths",
  "--color=always",
  "--syntax-highlight=on",
  "--display=side-by-side",
]

[merge]
command = "nvim"
args = ["-d", "{{ .Destination }}", "{{ .Source }}", "{{ .Target }}"]

[hooks.update.pre]
command = "chezmoi-scripts"
args = ["--inline", "--fetch"]

[hooks.apply.post]
command = "chezmoi-scripts"
args = ["--inline", "--apply"]

[hooks.re-add.pre]
command = "chezmoi-scripts"
args = ["--inline", "--commit"]

# vim: ft=toml
