# encoding=utf-8

# plugin
set-option -g @plugin 'tmux-plugins/tpm'
set-option -g @plugin 'tmux-plugins/tmux-sensible'
set-option -g @plugin 'tmux-plugins/tmux-pain-control'
set-option -g @pane_resize "10"
set-option -g @plugin 'tmux-plugins/tmux-copycat'
run '~/.tmux/plugins/tpm/tpm'

# prefix
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

# vi mode
set-option -g mode-keys vi
set-option -g status-keys vi

# history
set-option -g history-file '~/.tmux/history'
set-option -g history-limit 65535

# mouse
set-option -g mouse on

# clipboard
if-shell "[ $(uname) = 'Darwin' ]" {
  #set-option -g set-clipboard off
  set-option -g copy-command "pbcopy"
  bind-key -T copy-command-vi Enter send-keys -X copy-pipe-and-cancel "tmux show-buffer | pbcopy"
  unbind-key -T prefix ]
  bind-key -T prefix ] run-shell "tmux set-buffer \"$(pbpaste)\"; tmux paste-buffer -p"
}
if-shell "[ $(uname) = 'Linux' ]" {
  #set-option -g set-clipboard off
  set-option -g copy-command "xclip -selection clipboard"
  bind-key -T copy-command-vi Enter send-keys -X copy-pipe-and-cancel "tmux show-buffer | xclip -selection clipboard -i"
  unbind-key -T prefix ]
  bind-key -T prefix ] run-shell "tmux set-buffer \"$(xclip -selection clipboard -o)\"; tmux paste-buffer -p"
}

# pane
set-option -g pane-base-index 1
set-option -g pane-border-style fg=gray,bold,bg=black
set-option -g pane-active-border-style fg=yellow,bold,bg=black
set-option -g pane-border-lines simple
set-option -g pane-border-indicators both

# statusline
set-option -g status on
set-option -g status-position bottom
set-option -g status-interval 1
set-option -g status-style bg=black,bold
set-option -g status-justify left
set-option -g base-index 1
set-option -g automatic-rename on
set-option -g renumber-windows on
set-window-option -g window-status-style default
set-window-option -g window-status-separator "|"
set-window-option -g window-status-format "#I.#W"
set-window-option -g window-status-current-style default
set-window-option -g window-status-current-format " #[fg=yellow,bold]#I.#W "
set-option -g status-left-style default
set-option -g status-left-length 50
if-shell "uname | grep -q Darwin" \
    'set-option -g status-left "#(ipconfig getiflist | xargs ipconfig getifaddr) - "'
if-shell 'uname | grep -q Linux' \
    "set-option -g status-left \"#(nmcli -f IP4.ADDRESS device show | grep -v ^$ | grep -v 127.0.0.1 | awk '{ ORS=\\\" \\\";print $2 }') - "
set-option -g status-right-style default
set-option -g status-right-length 100
set-option -g status-right " - #(lsof -nP -iTCP -sTCP:LISTEN | awk '(NR>1){ print $9 }' | sort | uniq | awk '{ ORS=\" \";print $1 }')"
