#!/bin/zsh
# shellcheck shell=bash source=/dev/null

[[ -f "$HOME/.profile" ]] && source "$HOME/.profile"

ZDOTDIR="$XDG_CONFIG_HOME/zsh"

[[ -r "$HOME/.bash_aliases" ]] && source "$HOME/.bash_aliases"

# vim: ft=zsh
