#!/bin/bash
# shellcheck shell=bash disable=SC2139

alias -- -="cd -"
alias ~='cd ~'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias urlencode='python3 -c "import sys, urllib.parse; print(urllib.parse.quote(sys.argv[1]))"'
alias urldecode='python3 -c "import sys, urllib.parse; print(urllib.parse.unquote(sys.argv[1]))"'

command -v vim >/dev/null 2>&1 && alias vi=vim
# command -v nvim >/dev/null 2>&1 && alias vi=nvim

alias PATH='echo -e ${PATH//:/\\n}'
# alias PX="HTTP_PROXY=http://127.0.0.1:8118 HTTPS_PROXY=http://127.0.0.1:8118 SOCKS_PROXY=socks5://127.0.0.1:1080 ALL_PROXY=socks5://127.0.0.1:1080"
alias PX="HTTP_PROXY=http://127.0.0.1:7890 HTTPS_PROXY=http://127.0.0.1:7890 SOCKS_PROXY=socks5://127.0.0.1:7890 ALL_PROXY=socks5://127.0.0.1:7890"
alias NLH="LEFTHOOK=0"

if ls --color=auto >/dev/null 2>&1; then
	__COLOR_ARGS="--color=auto"
else
	__COLOR_ARGS="-G"
fi
alias ls="ls $__COLOR_ARGS"
alias la="ls -a"
alias ll="ls -l"

# unset COLORFLAG
