#!/bin/sh
# shellcheck shell=sh
#
# PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
# LANG="en_US.UTF-8"
# LC_ALL="en_US.UTF-8"
# export PAGER="less"
# export EDITOR="vim"
# export VISUAL="vim"
# # export TERM="xterm-256color"
#
# export XDG_CONFIG_HOME="$HOME/.config"
# export XDG_CACHE_HOME="$HOME/.cache"
# export XDG_DATA_HOME="$HOME/.local/share"
# export XDG_STATE_HOME="$HOME/.local/state"
#
# # HOMEBREW_VERBOSE=1
# export HOMEBREW_PREFIX="/usr/local"
# export HOMEBREW_BUNDLE_FILE="$XDG_CONFIG_HOME/homebrew/Brewfile"
# export HOMEBREW_NO_AUTO_UPDATE=1
# export HOMEBREW_NO_ENV_HINTS=1
# export HOMEBREW_NO_INSTALL_FROM_API=1
#
# export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
# export TMUX_PLUGIN_MANAGER_PATH="$XDG_DATA_HOME/tmux/plugins"
#
# # export LEFTHOOK=1
# # # export LEFTHOOK_VERBOSE=1
# # # export LEFTHOOK_OUTPUT="meta,summary,success,failure,execution,execution_out,execution_info,skips"
# # export LEFTHOOK_QUIET=meta,execution
#
# # LESS="-g -i -M -R -S -w -X -z-4"
# # command -v src-hilite-lesspipe.sh >/dev/null 2>&1 &&
# # 	LESSPIPE="$(command -v src-hilite-lesspipe.sh)" && LESSOPEN="| ${LESSPIPE} %s"
#
# # command -v tmux >/dev/null 2>&1 &&
# # 	[ -z "$TMUX" ] && [ -n "$SSH_TTY" ] && tmux attach -t ssh || tmux new -s ssh
#
# vim: ft=sh
