#!/bin/bash
# shellcheck shell=bash source=/dev/null

source "$HOME/.profile"

[[ $- != *i* ]] && return # if not running interactively, don't do anything

case "$TERM" in
*color)
  PS1=' \[\e[0;32m\]\]\u\[\e[0m\]\]@\[\e[0;35m\]\]\h\[\e[0m\]\]:\[\e[0;34m\]\]\w\[\e[0m\] \$ '
  ;;
*)
  PS1='\u@\h:\w \$ '
  ;;
esac

HISTCONTROL=ignoreboth # don't put duplicate lines or lines starting with space in the history.
shopt -s histappend    # Append to the Bash history file, rather than overwriting it
HISTSIZE=1000          # number of lines of history to store in memory
HISTFILESIZE=10000     # number of lines of history to store in the history file

[[ $DISPLAY ]] && shopt -s checkwinsize

[[ -r "$HOME/.bash_aliases" ]] && source "$HOME/.bash_aliases"

# vim: ft=bash
