#!/bin/bash
# shellcheck shell=bash

alias -- -="cd -"
alias ~='cd ~'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias urlencode='python3 -c "import sys, urllib.parse; print(urllib.parse.quote(sys.argv[1]))"'
alias urldecode='python3 -c "import sys, urllib.parse; print(urllib.parse.unquote(sys.argv[1]))"'

# alias P="HTTP_PROXY=http://127.0.0.1:8118 HTTPS_PROXY=http://127.0.0.1:8118 SOCKS_PROXY=socks5://127.0.1:1080 ALL_PROXY=socks5://127.0.0.1:1080"
alias P="HTTP_PROXY=http://127.0.0.1:7890 HTTPS_PROXY=http://127.0.0.1:7890 SOCKS_PROXY=socks5://127.0.1:7890 ALL_PROXY=socks5://127.0.0.1:7890"
