#!/bin/sh
# shellcheck shell=sh

PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
export PAGER="less"
export EDITOR="vim"
export VISUAL="vim"
# export TERM="xterm-256color"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export TMUX_PLUGIN_MANAGER_PATH="$XDG_DATA_HOME/tmux/plugins"

# command -v tmux >/dev/null 2>&1 &&
# 	[ -z "$TMUX" ] && [ -n "$SSH_TTY" ] && tmux attach -t ssh || tmux new -s ssh

# vim: ft=sh
