#!/bin/sh
# shellcheck source=/dev/null

# export XDG_CONFIG_HOME="$HOME/.config"

[ -f "/etc/X11/xinit/.Xresources" ] && xrdb -merge "/etc/X11/xinit/.Xresources"
[ -f "$HOME/.Xresources" ] && xrdb -merge "$HOME/.Xresources"

[ -f "/etc/X11/xinit/.Xmodmap" ] && xmodmap "/etc/X11/xinit/.Xmodmap"
[ -f "$HOME/.Xmodmap" ] && xmodmap "$HOME/.Xmodmap"

[ -d /etc/X11/xinit/xinitrc.d ] &&
	for fn in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$fn" ] && . "$fn"
	done
unset fn

session=${1:-i3}
case $session in
i3 | i3wm) exec i3 ;;
*) exec $1 ;;
esac
