#!/bin/zsh
# shellcheck shell=bash

PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"
XDG_CONFIG_HOME="$HOME/.config"
ZDOTDIR="$XDG_CONFIG_HOME/zsh"
# GITHUB_USERNAME=chg1f

# vim: set ft=zsh
