[colors]
foreground = "#ffffff"
background = "#000000"

ansi = [
  "#31322c",
  "#c12c1f",
  "#4f6f46",
  "#d6c560",
  "#2e59a7",
  "#814662",
  "#8aabcc",
  "#d5c8a0",
]
brights = [
  "#46433b",
  "#ba5140",
  "#779649",
  "#ece093",
  "#5976ba",
  "#995d7f",
  "#a3bbdb",
  "#dfd6b8",
]

# [colors]
# foreground = "#ffffff"
# background = "#16181a"
#
# cursor_bg = "#ffffff"
# cursor_fg = "#16181a"
# cursor_border = "#ffffff"
#
# selection_fg = "#ffffff"
# selection_bg = "#3c4048"
#
# scrollbar_thumb = "#16181a"
# split = "#16181a"
# brights = [
#   "#3c4048",
#   "#ff6e5e",
#   "#5eff6c",
#   "#f1ff5e",
#   "#5ea1ff",
#   "#bd5eff",
#   "#5ef1ff",
#   "#ffffff",
# ]
# ansi = [
#   "#16181a",
#   "#ff6e5e",
#   "#5eff6c",
#   "#f1ff5e",
#   "#5ea1ff",
#   "#bd5eff",
#   "#5ef1ff",
#   "#ffffff",
# ]
#
# # indexed = [ [16] = "#ffbd5e", [17] = "#ff6e5e" ]
