[settings]
# verbose = true
jobs = 8
env_file = '.env'
python.uv_venv_auto = true
pipx.uvx = true
lockfile = true

[tools]
# runtimes
node = "lts"
go = "1.25.4"
python = "latest"
uv = "latest"
rust = "latest"

# go toolchain
golangci-lint = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
"github:go-swagger/go-swagger" = "latest"

# lua tooling
"aqua:LuaLS/lua-language-server" = "latest"
"github:JohnnyMorganz/StyLua" = "latest"

# markdown tooling
"github:artempyanykh/marksman" = "latest"
"npm:markdown-toc" = "latest"
"npm:markdownlint-cli2" = "latest"

# protobuf tooling
protobuf = "latest"
protoc-gen-go = "latest"

# python tooling
"npm:pyright" = "latest"
"pipx:ruff" = "latest"
"pipx:sqlfluff" = "latest"

# rust tooling
"github:rust-lang/rust-analyzer" = "latest"

# shell tooling
"npm:bash-language-server" = "latest"
shellcheck = "latest"
shfmt = "latest"

# structured data tooling
"github:jqlang/jq" = "latest"
"github:mikefarah/yq" = "latest"
"github:tamasfe/taplo" = "latest"
"github:TomWright/dasel" = "latest"
"go:github.com/tidwall/jj/cmd/jj" = "latest"

# template tooling
gomplate = "latest"

# text tooling
"github:crate-ci/typos" = "latest"
"github:tekumara/typos-lsp" = "latest"

# typescript and node tooling
"npm:@vtsls/language-server" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"github:biomejs/biome" = "latest"

# workflow tooling
"github:evilmartians/lefthook" = "latest"

# cli helpers
bun = "latest"
fx = "latest"
hurl = "latest"
xh = "latest"
tree-sitter = "latest"
