#!zsh
# shellcheck shell=bash source=/dev/null disable=SC2034

LANG="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
EDITOR="vim"
VISUAL="vim"
PAGER="less"

export LESS="-g -i -w -M -R -F -X --mouse"
export LESSHISTFILE="$XDG_STATE_HOME/lesshst"
export MANPAGER="col -bx | bat -p -l man"
export HOMEBREW_PREFIX="$(brew --prefix)"
export HOMEBREW_BUNDLE_FILE="$XDG_CONFIG_HOME/homebrew/Brewfile"
export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_ENV_HINTS=1
export HOMEBREW_NO_INSTALL_FROM_API=1
export TMUX_PLUGIN_MANAGER_PATH="$XDG_DATA_HOME/tmux/plugins"
export FZF_DEFAULT_OPTS="--height=50% --layout=reverse --cycle --bind ctrl-f:preview-page-down,ctrl-b:preview-page-up,ctrl-e:preview-down,ctrl-y:preview-up"
export GOPATH="$XDG_DATA_HOME/go"

# # Set editor default keymap to vi (`-v`)
# bindkey -v
# zmodload -F zsh/terminfo +p:terminfo
# bindkey -M vicmd 'k' history-substring-search-up
# bindkey -M vicmd 'j' history-substring-search-down
# autoload -Uz edit-command-line
# zle -N edit-command-line
# bindkey -M vicmd 'v' edit-command-line
#
# ZSH_AUTOSUGGEST_MANUAL_REBIND=1
# bindkey '^l' autosuggest-accept
# bindkey '^h' autosuggest-clear

export ZIM_HOME="$(brew --prefix)/share/zim"
export ZIM_CONFIG_FILE="$ZDOTDIR/.zimrc"
# Install modules and update Zim # Define zmodule
[[ -s "$ZIM_HOME/zimfw.zsh" ]] && source "$ZIM_HOME/zimfw.zsh" init -q
# Source Zim
[[ -s "$ZIM_HOME/init.zsh" ]] && source "$ZIM_HOME/init.zsh"

# if command -v starship 2>&1 /dev/null ; then
# fi
eval "$(starship init zsh)"

# if command -v zsh-autosuggestions &> /dev/null; then
#   ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
#   ZSH_AUTOSUGGEST_STRATEGY=(history completion)
#   ZSH_AUTOSUGGEST_USE_ASYNC=true
#   source "$ZSH_AUTOSUGGEST_DIR/zsh-autosuggestions.zsh"
# fi

alias PX="HTTP_PROXY=http://127.0.0.1:7890 HTTPS_PROXY=http://127.0.0.1:7890 SOCKS_PROXY=socks5://127.0.0.1:7890 ALL_PROXY=socks5://127.0.0.1:7890"
alias NLH="LEFTHOOK=0"

alias http="http --check-status -pHBhbm"

# vim: set ft=zsh
