aliases: {}
substitute-path: []
max-string-len: 1000
max-array-values: 1000
show-location-expr: false
source-list-line-color: null
source-list-arrow-color: ""
source-list-keyword-color: ""
source-list-string-color: ""
source-list-number-color: ""
source-list-comment-color: ""
prompt-color: ""
source-list-tab-color: ""
stacktrace-function-color: ""
stacktrace-basename-color: ""
debug-info-directories:
    - /usr/lib/debug/.build-id
position: ""
tab: ""
trace-show-timestamp: false
